# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: make bootstrap
    command: make watch

github:
  # https://www.gitpod.io/docs/prebuilds/#configure-prebuilds
  prebuilds:
    master: true # enable for the default branch (even if it's not named "master")
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false

vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.5:9Wg0Glx/TwD8ElFBg+FKcQ==
    - esbenp.prettier-vscode@5.0.0:qca7d0cHbKkrkb5rvNlpcg==
    - flowtype.flow-for-vscode@1.5.0:AwOT6wgHTF43loZQCAUMLA==
