compressionLevel: mixed

conditions:
  BABEL_8_BREAKING:
    default: false
  USE_ESM:
    default: false

# Disable hardened mode. The Hardened mode will be run in the prepare-yarn-cache CI job.
enableHardenedMode: false

enableGlobalCache: true

# Disable postinstall scripts.
enableScripts: false

enableTransparentWorkspaces: false

nodeLinker: node-modules

packageExtensions:
  # @babel/preset-env depends on all these packages using the condition:
  # protocol, which does not properly propagate peer dependency requirements.
  # We know that we have the correct Babel version in the monorepo, so let's
  # just remove the peerDependency requirement to silence the warning.
  "@babel/plugin-proposal-private-property-in-object@*":
    peerDependencies:
      "@babel/core": null
  "@babel/plugin-syntax-async-generators@*":
    peerDependencies:
      "@babel/core": null
  "@babel/plugin-syntax-class-properties@*":
    peerDependencies:
      "@babel/core": null
  "@babel/plugin-syntax-class-static-block@*":
    peerDependencies:
      "@babel/core": null
  "@babel/plugin-syntax-dynamic-import@*":
    peerDependencies:
      "@babel/core": null
  "@babel/plugin-syntax-export-namespace-from@*":
    peerDependencies:
      "@babel/core": null
  "@babel/plugin-syntax-import-meta@*":
    peerDependencies:
      "@babel/core": null
  "@babel/plugin-syntax-json-strings@*":
    peerDependencies:
      "@babel/core": null
  "@babel/plugin-syntax-logical-assignment-operators@*":
    peerDependencies:
      "@babel/core": null
  "@babel/plugin-syntax-nullish-coalescing-operator@*":
    peerDependencies:
      "@babel/core": null
  "@babel/plugin-syntax-numeric-separator@*":
    peerDependencies:
      "@babel/core": null
  "@babel/plugin-syntax-object-rest-spread@*":
    peerDependencies:
      "@babel/core": null
  "@babel/plugin-syntax-optional-catch-binding@*":
    peerDependencies:
      "@babel/core": null
  "@babel/plugin-syntax-optional-chaining@*":
    peerDependencies:
      "@babel/core": null
  "@babel/plugin-syntax-private-property-in-object@*":
    peerDependencies:
      "@babel/core": null
  "@babel/plugin-syntax-top-level-await@*":
    peerDependencies:
      "@babel/core": null
  "@babel/plugin-syntax-unicode-sets-regex@*":
    peerDependencies:
      "@babel/core": null

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-babel-release-tool.cjs
    spec: "https://raw.githubusercontent.com/nicolo-ribaudo/yarn-plugin-babel-release-tool/main/bundles/%40yarnpkg/plugin-babel-release-tool.js"
  - path: .yarn/plugins/@yarnpkg/plugin-conditions.cjs
    spec: "https://raw.githubusercontent.com/nicolo-ribaudo/yarn-plugin-conditions/main/bundles/%40yarnpkg/plugin-conditions.js"

releaseTool:
  ignoreChanges:
    - "*.md"
    - "*.txt"
    - test/**
    - "**/test/**"
    - codemods/**
    - "@(!(native-modules|built-ins|plugins|package|corejs2-built-ins|corejs3-shipped-proposals|plugins-bugfixes)).json"
  implicitDependencies:
    "@babel/runtime":
      - "@babel/helpers"
    "@babel/runtime-corejs2":
      - "@babel/helpers"
    "@babel/runtime-corejs3":
      - "@babel/helpers"

unsafeHttpWhitelist:
  - localhost

yarnPath: .yarn/releases/yarn-4.0.1-git.20231104.hash-afacd23.cjs
