enableConstraintsChecks: true

# Disable hardened mode. The Hardened mode will be run in the prepare-yarn-cache CI job.
enableHardenedMode: false

# Disable postinstall scripts.
enableScripts: false

enableTransparentWorkspaces: false

nmMode: hardlinks-local

nodeLinker: node-modules

preferInteractive: true

releaseTool:
  ignoreChanges:
    - "*.md"
    - "*.txt"
    - test/**
    - "**/test/**"
    - codemods/**
    - "@(!(native-modules|built-ins|plugins|package|corejs2-built-ins|corejs3-shipped-proposals|plugins-bugfixes)).json"
  implicitDependencies:
    "@babel/runtime":
      - "@babel/helpers"
    "@babel/runtime-corejs3":
      - "@babel/helpers"

unsafeHttpWhitelist:
  - localhost
