coverage:
  parsers:
    javascript:
      enable_partials: yes
  status:
    project:
      default:
        target: "90%"
    patch:
      enabled: false
ignore:
  - packages/babel-types/src/*/generated/index.js
