/* This file is automatically generated by scripts/generators/archived-libs-typings.js */

declare module "@babel/plugin-syntax-async-functions" {
  import { declare } from "@babel/helper-plugin-utils";
  let exports: {default: ReturnType<typeof declare>};
  export = exports;
}
declare module "@babel/plugin-syntax-async-generators" {
  import { declare } from "@babel/helper-plugin-utils";
  let exports: {default: ReturnType<typeof declare>};
  export = exports;
}
declare module "@babel/plugin-syntax-bigint" {
  import { declare } from "@babel/helper-plugin-utils";
  let exports: {default: ReturnType<typeof declare>};
  export = exports;
}
declare module "@babel/plugin-syntax-class-properties" {
  import { declare } from "@babel/helper-plugin-utils";
  let exports: {default: ReturnType<typeof declare>};
  export = exports;
}
declare module "@babel/plugin-syntax-class-static-block" {
  import { declare } from "@babel/helper-plugin-utils";
  let exports: {default: ReturnType<typeof declare>};
  export = exports;
}
declare module "@babel/plugin-syntax-dynamic-import" {
  import { declare } from "@babel/helper-plugin-utils";
  let exports: {default: ReturnType<typeof declare>};
  export = exports;
}
declare module "@babel/plugin-syntax-exponentiation-operator" {
  import { declare } from "@babel/helper-plugin-utils";
  let exports: {default: ReturnType<typeof declare>};
  export = exports;
}
declare module "@babel/plugin-syntax-export-extensions" {
  import { declare } from "@babel/helper-plugin-utils";
  let exports: {default: ReturnType<typeof declare>};
  export = exports;
}
declare module "@babel/plugin-syntax-export-namespace-from" {
  import { declare } from "@babel/helper-plugin-utils";
  let exports: {default: ReturnType<typeof declare>};
  export = exports;
}
declare module "@babel/plugin-syntax-import-meta" {
  import { declare } from "@babel/helper-plugin-utils";
  let exports: {default: ReturnType<typeof declare>};
  export = exports;
}
declare module "@babel/plugin-syntax-json-strings" {
  import { declare } from "@babel/helper-plugin-utils";
  let exports: {default: ReturnType<typeof declare>};
  export = exports;
}
declare module "@babel/plugin-syntax-logical-assignment-operators" {
  import { declare } from "@babel/helper-plugin-utils";
  let exports: {default: ReturnType<typeof declare>};
  export = exports;
}
declare module "@babel/plugin-syntax-module-string-names" {
  import { declare } from "@babel/helper-plugin-utils";
  let exports: {default: ReturnType<typeof declare>};
  export = exports;
}
declare module "@babel/plugin-syntax-nullish-coalescing-operator" {
  import { declare } from "@babel/helper-plugin-utils";
  let exports: {default: ReturnType<typeof declare>};
  export = exports;
}
declare module "@babel/plugin-syntax-numeric-separator" {
  import { declare } from "@babel/helper-plugin-utils";
  let exports: {default: ReturnType<typeof declare>};
  export = exports;
}
declare module "@babel/plugin-syntax-object-rest-spread" {
  import { declare } from "@babel/helper-plugin-utils";
  let exports: {default: ReturnType<typeof declare>};
  export = exports;
}
declare module "@babel/plugin-syntax-optional-catch-binding" {
  import { declare } from "@babel/helper-plugin-utils";
  let exports: {default: ReturnType<typeof declare>};
  export = exports;
}
declare module "@babel/plugin-syntax-optional-chaining" {
  import { declare } from "@babel/helper-plugin-utils";
  let exports: {default: ReturnType<typeof declare>};
  export = exports;
}
declare module "@babel/plugin-syntax-private-property-in-object" {
  import { declare } from "@babel/helper-plugin-utils";
  let exports: {default: ReturnType<typeof declare>};
  export = exports;
}
declare module "@babel/plugin-syntax-top-level-await" {
  import { declare } from "@babel/helper-plugin-utils";
  let exports: {default: ReturnType<typeof declare>};
  export = exports;
}
declare module "@babel/plugin-syntax-trailing-function-commas" {
  import { declare } from "@babel/helper-plugin-utils";
  let exports: {default: ReturnType<typeof declare>};
  export = exports;
}
declare module "@babel/plugin-syntax-unicode-sets-regex" {
  import { declare } from "@babel/helper-plugin-utils";
  let exports: {default: ReturnType<typeof declare>};
  export = exports;
}
declare module "@babel/plugin-syntax-decimal" {
  import { declare } from "@babel/helper-plugin-utils";
  let exports: {default: ReturnType<typeof declare>};
  export = exports;
}
declare module "@babel/plugin-syntax-import-reflection" {
  import { declare } from "@babel/helper-plugin-utils";
  let exports: {default: ReturnType<typeof declare>};
  export = exports;
}
