name: Package Manager
on:
  pull_request:
    paths:
      # Ensure packageManager field contains the correct yarn version and integrity hash.
      - "package.json"
      - ".yarn/releases/*"

jobs:
  yarn_integrity:
    name: Ensure yarn integrity
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - run: |
          node ./scripts/ensure-yarn-version-integrity.ts
