name: PR Yarn integrity check
on:
  pull_request:
    paths:
      # Ensure packageManager field contains the correct yarn version and integrity hash.
      - "package.json"
      - ".yarn/releases/*"

jobs:
  integrity:
    name: Check Yarn integrity
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Ensure yarn integrity
        run: |
          node ./scripts/ensure-yarn-version-integrity.ts
